### ISSUE TITLE
Cleanups for CanJS to be build as ESM

### ISSUE THREAD

**Issue by frank-dspeed** [stealify/canes#4]
## Todo
- [ ] All Modules need to use named exports pattern with no sideeffects.
- [ ] All Modules should have clean ES5 module output named
- [ ] All files should be absolute references. and directly in core.
- [ ] make the whole code base transpil able to ESM
